export default {
  info: {
    music: {
      tts: 'Playing your favorite Song',
      response: 'Playing your Favourite Song',
      template: 'info',
      suggestions: ['Hey Bixby, dismiss'],
      img: '/static/Images/results/info/lostInTrans.png',
    },
    fitbitQuery: {
      tts: 'looks like you took 9,738 steps, you have 262 steps left to hit the goal ',
      response: 'You took 9,738 steps',
      template: 'info',
      suggestions: ['Hey Bixby, dismiss'],
      img: '/static/Images/results/info/lostInTrans.png',
    },
    lostintrans: {
      template: 'info',
      type: 'lostmovie',
      response: 'Here’s what I found for Lost in Translation',
      img: '/static/Images/results/info/lostInTrans.png',
    },
    fitbitSummary: {
      template: 'info',
      type: 'fitbit',
      response: 'Here is your fit bit summary',
      suggestions: ['Hey Bixby, go to health & wellmess', 'Hey Bixby, dismiss'],
      img: '/static/Images/results/info/fitbit_summary.png',
    },
    fitbitSleep: {
      template: 'info',
      type: 'fitbit',
      suggestions: ['Hey Bixby, show me my Fitbit summary', 'Hey Bixby, dismiss'],
      response: 'Here is your Sleep Quality from Fitbit',
      img: '/static/Images/results/info/fitbit_sleep_quality.png',
    },
    everest: {
      template: 'info',
      type: 'everest',
      suggestions: ['Hey Bixby, dismiss'],
      tts: 'Mount Everest is 8848 meters tall',
      response: 'Mount Everest is 8848 meters tall',
      img: '/static/Images/results/info/everest.png',
    },
    weatherport: {
      template: 'info',
      type: 'weather',
      suggestions: ['Hey Bixby, dismiss'],
      response: 'Here is your 7 days forecast in Portland',
      tts: 'sure portland',
      img: '/static/Images/results/info/weather-portland.png',
    },
    weatherweekend: {
      template: 'info',
      type: 'weather',
      response: 'Here is your 7-day forcast',
      suggestions: ['Hey Bixby, dismiss'],
      tts: 'Here\'s the weather this week',
      img: '/static/Images/results/info/weather-weekend.png',
    },
    weathertoday: {
      template: 'info',
      type: 'weather',
      suggestions: ['Hey Bixby, dismiss'],
      response: 'Here is today’s forecast',
      img: '/static/Images/results/info/weather-today.png',
    },
    measure: {
      template: 'info',
      suggestions: ['Hey Bixby, dismiss'],
      type: 'measure',
      tts: '1 cup is equal to 8 fluid ounces',
      response: '1 cup is equal to 8 fluid ounces',
      img: '/static/Images/results/info/measure.png',
    },
  },
};
