export default {
  michael: {
    list: ['default', 'mjSong1', 'mjSong2', 'mjSong3', 'mjSong4', 'mjSong5', 'mjSong6'],
    default: {
      artist: 'Michael Jackson',
      song: 'Black or White',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          logoType: 'big',
          bottomText: 'Black or White',
          logo: '/static/Images/home/icons/morning/spotify.png',
          img: '/static/Images/spotify/songs/thumbnail/michael.png',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art3.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/michael.png',
      url: '/resources/audio/soundtrack/MJ_BlackorWhite.mp3',
    },
    mjSong1: {
      artist: 'Michael Jackson',
      song: 'Man in the Mirror',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Man in the Mirror',
          logoType: 'big',
          logo: '/static/Images/home/icons/morning/spotify.png',
          img: '/static/Images/spotify/songs/thumbnail/MJ_thriller25.jpg',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art3.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/MJ_thriller25.jpg',
      url: '/resources/audio/soundtrack/MJ_Maninthemirror.mp3',
    },
    mjSong2: {
      artist: 'Michael Jackson',
      song: 'Scream',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Scream',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/MJ_bad25.jpg',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art3.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/MJ_bad25.jpg',
      url: '/resources/audio/soundtrack/MJ_scream.mp3',
    },
    mjSong3: {
      artist: 'Michael Jackson',
      song: 'Smooth criminal',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Smooth criminal',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/MJ_thriller25.jpg',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art3.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/MJ_thriller25.jpg',
      url: '/resources/audio/soundtrack/MJ_smooth_criminal.mp3',
    },
    mjSong4: {
      artist: 'Michael Jackson',
      song: 'Thriller',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Thriller',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/MJ_bad25.jpg',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art3.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/MJ_bad25.jpg',
      url: '/resources/audio/soundtrack/MJ_Thriller.mp3',
    },
    mjSong5: {
      artist: 'Michael Jackson',
      song: 'Beat it',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Beat it',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/michael.png',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art3.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/michael.png',
      url: '/resources/audio/soundtrack/MJ_beatit.mp3',
    },
    mjSong6: {
      artist: 'Michael Jackson',
      song: 'Billie Jean',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Billie Jean',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/MJ_bad25.jpg',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art3.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/MJ_bad25.jpg',
      url: '/resources/audio/soundtrack/MJ_billieJean.mp3',
    },
  },
  ariana: {
    list: ['default'],
    default: {
      artist: 'Ariana Grande',
      song: 'No Tears Left to Cry',
      save: {
        rmvApp: 'spotify',
        index: 0,
        pageIdx: 2,
        elapsedTime: 0,
        total: 0,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'No Tears Left to Cry',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/ariana.png',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art3.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/ariana.png',
      url: '/resources/audio/soundtrack/MJ_beatit.mp3',
    },
  },
  coldplay: {
    list: ['default'],
    default: {
      artist: 'Cold Play',
      song: 'Strawberry Swing',
      save: {
        rmvApp: 'spotify',
        index: 0,
        pageIdx: 2,
        elapsedTime: 0,
        total: 0,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Strawberry Swing',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/strawberry.png',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art4.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/strawberry.png',
      url: '/resources/audio/soundtrack/Coldplay_StrawberrySwing.mp3',
    },
  },
  classical: {
    list: ['default', 'classicSong1'],
    default: {
      artist: 'alexis french',
      song: 'Blue bird',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Blue bird',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/alexis_ffrench_bluebird.jpg',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art1.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/alexis_ffrench_bluebird.jpg',
      url: '/resources/audio/soundtrack/alexis_ffrench_bluebird.mp3',
    },
    classicSong1: {
      artist: 'Beethoven',
      song: 'Moonlight Sonata',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Moonlight Sonata',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/classic.png',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art1.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/classic.png',
      url: '/resources/audio/soundtrack/beethoven_moonlight_sonata.mp3',
    },
  },
  pharrell: {
    list: ['default'],
    default: {
      artist: 'Pharrell Williams',
      song: 'Happy',
      save: {
        rmvApp: 'spotify',
        index: 0,
        elapsedTime: 0,
        total: 0,
        pageIdx: 2,
        details: {
          action: {
            category: 'spotify',
          },
          bottomText: 'Happy',
          logo: '/static/Images/home/icons/morning/spotify.png',
          logoType: 'big',
          img: '/static/Images/spotify/songs/thumbnail/phareell.png',
        },
        driverTheme: 'dark',
      },
      art: '/static/Images/spotify/songs/art/art2.png',
      thumbnail: '/static/Images/spotify/songs/thumbnail/phareell.png',
      url: '/resources/audio/soundtrack/Pharel_Williams_happy.mp3',
    },
  },
};
