export default {
  gridlist: ['now', 'upcoming', 'contWatch', 'music', 'apps', 'avengers'],
  now: {
    items: ['espn', 'cnn', 'ytube1', 'ytube2'],
    title: 'On Now',
    name: 'now',
    itemType: 'sqrThumb',
    selIdx: 0,
    espn: {
      title: '2018 NHL Playoffs: San Jose',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/espn.png',
      thumbnail: '/static/Images/home/foryou/onNow/espn1.png',
      startTime: 'live',
    },
    cnn: {
      title: 'CNN Live',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 7:00PM',
      logo: '/static/Images/home/foryou/icons/cnn.png',
      thumbnail: '/static/Images/home/foryou/onNow/cnn1.png',
      startTime: 'live',
    },
    ytube1: {
      title: 'American Idol 2018',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube1.png',
      startTime: 'live',
    },
    ytube2: {
      title: 'Wild India',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube2.png',
      startTime: 'live',
    },
  },
  upcoming: {
    items: ['twitch', 'ytube1', 'espn', 'amazon'],
    title: 'Upcoming',
    selIdx: 0,
    name: 'upcoming',
    itemType: 'sqrThumb',
    twitch: {
      title: 'Fnatic vs. Flash Wolves',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'Group Stage Day 4',
      logo: '/static/Images/home/foryou/icons/twitch.png',
      thumbnail: '/static/Images/home/foryou/upcoming/twitch.png',
      startTime: '8:00 PM',
    },
    ytube1: {
      title: 'CNN Live',
      gist: 'Tennis Channel ATP Final',
      subtitle: '2018 Barclays ATP World Tour',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/upcoming/ytube1.png',
      startTime: '9:00 PM',
    },
    espn: {
      title: 'American Idol 2018',
      gist: 'NBA Finals',
      subtitle: 'Warriors vs. Rockets',
      logo: '/static/Images/home/foryou/icons/espn.png',
      thumbnail: '/static/Images/home/foryou/upcoming/espn1.png',
      startTime: '8:00 PM',
    },
    amazon: {
      title: 'Wild India',
      gist: 'iZombie',
      subtitle: 'Season 5',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/upcoming/amazon.png',
      startTime: '8:00 PM',
    },
  },
  contWatch: {
    name: 'continue',
    selIdx: 0,
    items: ['ytube1', 'hulu', 'amazon', 'hulu1'],
    title: 'Continue Watching',
    itemType: 'sqrThumb',
    ytube1: {
      title: 'Black Mirror',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S3 E2',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/continue/ytube1.png',
    },
    hulu: {
      title: 'The Expanse',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S2 E5',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu.png',
    },
    amazon: {
      title: 'Avengers Infinity War',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '2018',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/continue/amazon.png',
    },
    hulu1: {
      title: 'Stranger Things',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu1.png',
    },
  },
  music: {
    items: ['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'item7'],
    itemType: 'recThumb',
    selIdx: 0,
    name: 'music',
    title: 'Recent Music',
    item1: {
      title: 'A Moment',
      subtitle: 'Odesza',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item1.png',
    },
    item2: {
      title: 'California',
      subtitle: 'Diplo',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item2.png',
    },
    item3: {
      title: 'No Reason',
      subtitle: 'Giraffage',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item3.png',
    },
    item4: {
      title: 'Hard to Say No',
      subtitle: 'Chromeo',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item4.png',
    },
    item5: {
      title: 'Ivory',
      subtitle: 'Tez Candey',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item5.png',
    },
    item6: {
      title: 'Your Daily Mix',
      subtitle: '',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item6.png',
    },
    item7: {
      title: 'Seve',
      subtitle: 'Tez Candey',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item7.png',
    },
  },
  avengers: {
    items: ['item1', 'item2', 'item3', 'item4'],
    title: 'Avengers',
    selIdx: 0,
    name: 'avengers',
    itemType: 'sqrThumb',
    item1: {
      title: 'Captain America: Civil War',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/avenger/item1.png',
    },
    item2: {
      title: 'Avengers: Age of Ultron',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/avenger/item2.png',
    },
    item3: {
      title: 'Avengers Infinity War',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/avenger/item3.png',
    },
    item4: {
      title: 'The Avengers',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/avenger/item4.png',
    },
  },
  apps: {
    items: ['netflix', 'hulu', 'amazon', 'spotify', 'youtube', 'espn'],
    itemType: 'sqr',
    selIdx: 0,
    name: 'apps',
    title: 'Recent Apps',
    netflix: {
      thumbnail: '/static/Images/home/foryou/apps/netflix.png',
      title: 'NetFlix',
    },
    hulu: {
      thumbnail: '/static/Images/home/foryou/apps/hulu.png',
      title: 'Hulu',
    },
    amazon: {
      thumbnail: '/static/Images/home/foryou/apps/amazon.png',
      title: 'Amazon',
    },
    spotify: {
      thumbnail: '/static/Images/home/foryou/apps/spotify.png',
      title: 'Spotify',
    },
    youtube: {
      thumbnail: '/static/Images/home/foryou/apps/youtube.png',
      title: 'Fitbit',
    },
    espn: {
      thumbnail: '/static/Images/home/foryou/apps/espn.png',
      title: 'MasterClass',
    },
  },
  pages: {
    pagination: ['page-1', 'page-2', 'page-3'],
    focusIdx: 0,
    details: {
      'page-1': {
        title: 'page-1',
        suggestions: ['Hey Bixby, continue watching The Handmaid’s Tale'],
        nav: [
          ['poster', 'tile', 'tile'],
          ['poster', 'thumbnail1', 'thumbnail2'],
        ],
        content: ['westworld', 'netflix', 'hulu', 'hbo'],
        westworld: {
          type: 'poster',
          template: 'poster',
          contentType: 'simple',
          details: {
            full: true,
            video: '/resources/videos/smartscreen/TV_Shows_1_Westworld.mp4',
            poster: '/static/Images/home/posters/morning/westw.png',
            text1: '<span><span style="color: rgba(255,97,97,1);">Westworld</span> <br> <span>2 Seasons | 20 Episodes</span></span>',
            logo: '/static/Images/home/foryou/slidesIcons/amazon.png',
            logoType: 'sqr',
            img: '',
          },
        },
        netflix: {
          type: 'tile',
          template: 'tile',
          contentType: 'simple',
          details: {
            full: 'partial',
            action: {
              category: 'hulu',
              subcategory: 'home',
              content: 'handmaids',
            },
            topLeftText: '<span class="bold-top-text">Continue Watching</span>',
            bottomText: '<span><span style="color: rgba(255,97,97,1);">Stranger Things</span>',
            tile: '/static/Images/home/tile/morning/stranger.png',
            logo: '/static/Images/home/foryou/slidesIcons/netflix.png',
            logoType: 'rect',
            img: '',
          },
        },
        hbo: {
          type: 'thumbnail2',
          template: 'thumbnail',
          contentType: 'cp',
          details: {
            full: 'full',
            icon: '',
            topLeftText: '<span class="bold-top-text">sponsored</span>',
            bottomText: '',
            logoType: 'sqr-2',
            logo: '/static/Images/home/foryou/slidesIcons/hbo.png',
            img: '/static/Images/home/thumbnail/morning/grace.png',
          },
        },
        hulu: {
          type: 'thumbnail1',
          template: 'thumbnail',
          contentType: 'cp',
          details: {
            full: 'full',
            bottomText: '',
            icon: '',
            logo: '/static/Images/home/foryou/slidesIcons/hulu.png',
            img: '/static/Images/home/thumbnail/morning/serena.png',
          },
        },
      },
      'page-2': {
        title: 'page-2',
        suggestions: ['Hey Bixby, go to Fitbit'],
        content: ['netflix', 'hbo'],
        nav: [
          ['hTile', 'poster', 'poster'],
          ['hTile', 'poster', 'poster'],
        ],
        netflix: {
          type: 'hTile',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: true,
            hTile: '/static/Images/home/hTile/morning/flash.png',
            text1: '<span style="color:white">The Flash</span>',
            logo: '/static/Images/home/foryou/slidesIcons/netflix.png',
            logoType: 'sqr',
            img: '',
          },
        },
        hbo: {
          type: 'poster',
          template: 'poster',
          contentType: 'simple',
          details: {
            full: true,
            video: '/resources/videos/smartscreen/TV_Shows_2_Six_feet_under.mp4',
            poster: '/static/Images/home/posters/morning/sixfeet.png',
            text1: '<span><span style="color: rgba(255,97,97,1);">Six Feet Under</span><br><span>5 Seasons | 63 Episodes</span></span>',
            logo: '/static/Images/home/foryou/slidesIcons/hbo-b.png',
            logoType: 'sqr',
            img: '',
          },
        },
      },
      'page-3': {
        title: 'page-3',
        suggestions: ['Hey Bixby, play my Classical Playlist'],
        content: ['hbo', 'got', 'hulu', 'hbo1', 'netflix'],
        nav: [
          ['hTile', 'tile', 'tile', 'hTile1'],
          ['hTile', 'thumbnail1', 'thumbnail2', 'hTile1'],
        ],
        hbo: {
          type: 'hTile',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: true,
            video: '/resources/videos/smartscreen/TV_Shows_3_True_detective.mp4',
            hTile: '/static/Images/home/hTile/morning/detective.png',
            text1: '<span style="color:white">True Detective</span>',
            logo: '/static/Images/home/foryou/slidesIcons/hbo.png',
            logoType: 'sqr',
            img: '',
          },
        },
        got: {
          type: 'tile',
          template: 'tile',
          contentType: 'simple',
          details: {
            full: true,
            tile: '/static/Images/home/tile/morning/got.png',
            bottomText: '<span class="bold-text">Game of Thrones</span>',
            logo: '/static/Images/home/foryou/slidesIcons/hbo-b.png',
            logoType: 'rect-3',
            img: '/static/Images/home/page1/poster.png',
          },
        },
        netflix: {
          type: 'hTile1',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: false,
            hTile: '/static/Images/home/hTile/morning/jane.png',
            text1: '<span style="color:black"><span style="color: rgba(255,97,97,1);">Jane the Virgin</span>Trek</span>',
            logo: '/static/Images/home/foryou/slidesIcons/netflix.png',
            logoType: 'sqr',
            img: '',
          },
        },
        spotify: {
          type: 'thumbnail1',
          template: 'thumbnail',
          contentType: 'cp',
          details: {
            full: 'full',
            icon: '',
            bottomText: '',
            logoType: 'big',
            logo: '/static/Images/home/foryou/slidesIcons/spotify.png',
          },
        },
        hbo1: {
          type: 'thumbnail2',
          template: 'thumbnail',
          contentType: 'cp-type-1',
          details: {
            full: 'full',
            icon: '',
            bottomText: '',
            logoType: 'text-big',
            logo: '/static/Images/home/foryou/slidesIcons/hbo.png',
            img: '/static/Images/home/thumbnail/morning/true.png',
          },
        },
        hulu: {
          full: true,
          type: 'thumbnail1',
          template: 'thumbnail',
          contentType: 'cp-type-1',
          details: {
            icon: '',
            bottomText: '',
            full: 'full',
            logoType: 'text-big',
            logo: '/static/Images/home/foryou/slidesIcons/hulu.png',
            img: '/static/Images/home/thumbnail/morning/grey.png',
          },
        },
      },
      'page-4': {
        title: 'page-4',
        template: 'ignore',
        content: ['map', 'fitness', 'match'],
        map: {
          img: '/static/Images/home/foryou/info1.png',
        },
        fitness: {
          img: '/static/Images/home/foryou/info2.png',
        },
        match: {
          img: '/static/Images/home/foryou/info3.png',
        },
      },
    },
  },
};
