export default {
  gridlist: ['now', 'upcoming', 'contWatch', 'drama', 'animated'],
  now: {
    items: ['espn', 'cnn', 'ytube1', 'ytube2'],
    title: 'CONTINUE WATCHING',
    name: 'now',
    itemType: 'sqrtile',
    espn: {
      title: 'Star Trek: Discovery',
      gist: 'S1 E1  &middot; The Vulcan Hello',
      subtitle: '6:00 - 8:00PM',
      progress: '40',
      progressColor: 'white',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/onNow/espn1.png',
      startTime: 'live',
    },
    cnn: {
      title: 'Atlanta',
      gist: 'S2 E11  ·  Crabs in a Barrel',
      subtitle: '6:00 - 7:00PM',
      progress: '20',
      progressColor: 'white',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/onNow/cnn1.png',
      startTime: 'live',
    },
    ytube1: {
      title: 'Runaways',
      gist: 'S1 E1  ·  Reunion',
      subtitle: '6:00 - 8:00PM',
      progress: '60',
      progressColor: 'white',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube1.png',
      startTime: 'live',
    },
    ytube2: {
      title: 'Roseanne',
      gist: 'S10 E9  ·  Knee Deep',
      progress: '50',
      next: 'New Episode',
      progressColor: 'white',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube2.png',
      startTime: 'live',
    },
  },
  upcoming: {
    items: ['twitch', 'ytube1', 'espn', 'amazon', 'item5'],
    title: 'ON NOW',
    name: 'upcoming',
    itemType: 'sqrThumb',
    twitch: {
      title: 'American’s Got Talent',
      progress: '80',
      progressColor: 'red',
      gist: '6:00 - 7:00PM',
      subtitle: 'Group Stage Day 4',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/upcoming/twitch.png',
      startTime: '8:00 PM',
    },
    ytube1: {
      title: 'Beat & Shazam',
      progress: '30',
      progressColor: 'red',
      gist: '6:00 - 7:00PM',
      subtitle: '2018 Barclays ATP World Tour',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/upcoming/ytube1.png',
      startTime: '9:00 PM',
    },
    espn: {
      title: 'Star Trek: Discovery',
      progress: '70',
      progressColor: 'red',
      gist: '6:00 - 7:00PM',
      subtitle: 'Warriors vs. Rockets',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/upcoming/espn1.png',
      startTime: '8:00 PM',
    },
    amazon: {
      title: 'The Big Bang Theory',
      gist: '6:30 - 7:00PM',
      subtitle: 'Season 5',
      progress: '10',
      progressColor: 'red',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/upcoming/amazon.png',
      startTime: '8:00 PM',
    },
    item5: {
      title: 'Star Trek:',
      progress: '20',
      progressColor: 'red',
      gist: '6:00 - 7:00PM',
      subtitle: 'Season 5',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/upcoming/item5.png',
      startTime: '8:00 PM',
    },
  },
  contWatch: {
    name: 'continue',
    items: ['ytube1', 'hulu', 'amazon', 'hulu1', 'item5'],
    title: 'COMEDY',
    itemType: 'sqrThumb',
    ytube1: {
      title: 'Red Oaks',
      gist: '1 Season',
      subtitle: 'S3 E2',
      logo: '/static/Images/home/foryou/icons/hbo.png',
      thumbnail: '/static/Images/home/foryou/continue/ytube1.png',
    },
    hulu: {
      title: 'Catastrophe',
      gist: '2 Seasons',
      subtitle: 'S2 E5',
      logo: '/static/Images/home/foryou/icons/hbo.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu.png',
    },
    amazon: {
      title: 'Conversations In L.A.',
      gist: '1 Season',
      subtitle: '2018',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/continue/amazon.png',
    },
    hulu1: {
      title: 'Parks and Recreation',
      gist: '3 Seasons',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu1.png',
    },
    item5: {
      title: 'Star Trek:',
      gist: '1 Season',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/continue/item5.png',
    },
  },
  drama: {
    name: 'drama',
    items: ['ytube1', 'hulu', 'amazon', 'hulu1', 'item5'],
    title: 'DRAMA',
    itemType: 'sqrThumb',
    ytube1: {
      title: 'The Man in the High Castle',
      gist: '2 Seasons',
      subtitle: 'S3 E2',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/drama/item1.png',
    },
    hulu: {
      title: 'The Handmaid\'s Tale',
      gist: '2 Seasons',
      subtitle: 'S2 E5',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/drama/item2.png',
    },
    amazon: {
      title: 'Black Mirror',
      gist: '4 Seasons',
      subtitle: '2018',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/drama/item3.png',
    },
    hulu1: {
      title: 'Runaways',
      gist: '1 Season',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/drama/item4.png',
    },
    item5: {
      title: 'Star Trek:',
      gist: '2 Seasons',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/drama/item5.png',
    },
  },
  animated: {
    name: 'ANIMATED',
    items: ['item1', 'item2', 'item3', 'item4'],
    title: 'ANIMATED',
    itemType: 'sqrThumb',
    item1: {
      title: 'Los Simpson',
      gist: '30 Seasons',
      subtitle: 'S3 E2',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/animated/item1.png',
    },
    item2: {
      title: 'South Park',
      gist: '6 Seasons',
      subtitle: 'S2 E5',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/animated/item2.png',
    },
    item3: {
      title: 'Rick and Morty',
      gist: '1 Season',
      subtitle: '2018',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/animated/item3.png',
    },
    item4: {
      title: 'Family Guy',
      gist: '6 Seasons',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/hbo.png',
      thumbnail: '/static/Images/home/foryou/animated/item4.png',
    },
    item5: {
      title: 'Star Trek:',
      gist: '2 Seasons',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/netflix.png',
      thumbnail: '/static/Images/home/foryou/animated/item5.png',
    },
  },
};
