export default {
  gridlist: ['now', 'upcoming', 'contWatch', 'music', 'apps', 'avengers'],
  now: {
    items: ['espn', 'cnn', 'ytube1', 'ytube2'],
    title: 'On Now',
    name: 'now',
    itemType: 'sqrThumb',
    espn: {
      title: '2018 NHL Playoffs: San Jose',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      progress: '40',
      extraImg: ['/static/Images/home/foryou/slidesIcons/live.png'],
      logo: '/static/Images/home/foryou/icons/espn.png',
      thumbnail: '/static/Images/home/foryou/onNow/espn1.png',
      startTime: 'live',
    },
    cnn: {
      title: 'CNN Live',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 7:00PM',
      progress: '20',
      extraImg: ['/static/Images/home/foryou/slidesIcons/live.png'],
      logo: '/static/Images/home/foryou/icons/cnn.png',
      thumbnail: '/static/Images/home/foryou/onNow/cnn1.png',
      startTime: 'live',
    },
    ytube1: {
      title: 'American Idol 2018',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      progress: '60',
      extraImg: ['/static/Images/home/foryou/slidesIcons/live.png'],
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube1.png',
      startTime: 'live',
    },
    ytube2: {
      title: 'Wild India',
      gist: 'Sharks vs. Anaheim Ducks',
      progress: '50',
      subtitle: '6:00 - 8:00PM',
      extraImg: ['/static/Images/home/foryou/slidesIcons/live.png'],
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube2.png',
      startTime: 'live',
    },
  },
  upcoming: {
    items: ['twitch', 'ytube1', 'espn', 'amazon'],
    title: 'Upcoming',
    name: 'upcoming',
    itemType: 'sqrThumb',
    twitch: {
      title: 'Fnatic vs. Flash Wolves',
      extraImg: ['/static/Images/home/foryou/slidesIcons/9pm.png'],
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'Group Stage Day 4',
      logo: '/static/Images/home/foryou/icons/twitch.png',
      thumbnail: '/static/Images/home/foryou/upcoming/twitch.png',
      startTime: '8:00 PM',
    },
    ytube1: {
      title: 'CNN Live',
      gist: 'Tennis Channel ATP Final',
      extraImg: ['/static/Images/home/foryou/slidesIcons/8pm.png'],
      subtitle: '2018 Barclays ATP World Tour',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/upcoming/ytube1.png',
      startTime: '9:00 PM',
    },
    espn: {
      title: 'American Idol 2018',
      gist: 'NBA Finals',
      extraImg: ['/static/Images/home/foryou/slidesIcons/8pm.png'],
      subtitle: 'Warriors vs. Rockets',
      logo: '/static/Images/home/foryou/icons/espn.png',
      thumbnail: '/static/Images/home/foryou/upcoming/espn1.png',
      startTime: '8:00 PM',
    },
    amazon: {
      title: 'Wild India',
      gist: 'iZombie',
      subtitle: 'Season 5',
      extraImg: ['/static/Images/home/foryou/slidesIcons/8pm.png'],
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/upcoming/amazon.png',
      startTime: '8:00 PM',
    },
  },
  contWatch: {
    name: 'continue',
    items: ['ytube1', 'hulu', 'amazon', 'hulu1'],
    title: 'Continue Watching',
    itemType: 'sqrThumb',
    ytube1: {
      title: 'Black Mirror',
      gist: 'Sharks vs. Anaheim Ducks',
      progress: 30,
      progressColor: 'white',
      subtitle: 'S3 E2',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/continue/ytube1.png',
    },
    hulu: {
      title: 'The Expanse',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S2 E5',
      progress: 50,
      progressColor: 'white',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu.png',
    },
    amazon: {
      title: 'Avengers Infinity War',
      extraImg: ['/static/Images/home/foryou/slidesIcons/3star.png'],
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '2018',
      progress: 70,
      progressColor: 'white',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/continue/amazon.png',
    },
    hulu1: {
      title: 'Stranger Things',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S1 E6',
      progress: 40,
      progressColor: 'white',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu1.png',
    },
  },
  music: {
    items: ['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'item7'],
    itemType: 'recThumb',
    name: 'music',
    title: 'Recent Music',
    item1: {
      title: 'A Moment',
      subtitle: 'Odesza',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item1.png',
    },
    item2: {
      title: 'California',
      subtitle: 'Diplo',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item2.png',
    },
    item3: {
      title: 'No Reason',
      subtitle: 'Giraffage',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item3.png',
    },
    item4: {
      title: 'Hard to Say No',
      subtitle: 'Chromeo',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item4.png',
    },
    item5: {
      title: 'Ivory',
      subtitle: 'Tez Candey',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item5.png',
    },
    item6: {
      title: 'Your Daily Mix',
      subtitle: '',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item6.png',
    },
    item7: {
      title: 'Seve',
      subtitle: 'Tez Candey',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item7.png',
    },
  },
  avengers: {
    items: ['item1', 'item2', 'item3', 'item4'],
    title: 'Avengers',
    name: 'avengers',
    itemType: 'sqrThumb',
    item1: {
      title: 'Captain America: Civil War',
      extraImg: ['/static/Images/home/foryou/slidesIcons/3star.png'],
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/avenger/item1.png',
    },
    item2: {
      title: 'Avengers: Age of Ultron',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      extraImg: ['/static/Images/home/foryou/slidesIcons/3star.png'],
      thumbnail: '/static/Images/home/foryou/avenger/item2.png',
    },
    item3: {
      title: 'Avengers Infinity War',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      extraImg: ['/static/Images/home/foryou/slidesIcons/3star.png'],
      thumbnail: '/static/Images/home/foryou/avenger/item3.png',
    },
    item4: {
      title: 'The Avengers',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/avenger/item4.png',
    },
  },
  apps: {
    items: ['netflix', 'hulu', 'amazon', 'spotify', 'youtube', 'espn'],
    itemType: 'sqr',
    name: 'apps',
    title: 'Recent Apps',
    netflix: {
      thumbnail: '/static/Images/home/foryou/apps/netflix.png',
      title: 'NetFlix',
    },
    hulu: {
      thumbnail: '/static/Images/home/foryou/apps/hulu.png',
      title: 'Hulu',
    },
    amazon: {
      thumbnail: '/static/Images/home/foryou/apps/amazon.png',
      title: 'Amazon',
    },
    spotify: {
      thumbnail: '/static/Images/home/foryou/apps/spotify.png',
      title: 'Spotify',
    },
    youtube: {
      thumbnail: '/static/Images/home/foryou/apps/youtube.png',
      title: 'Fitbit',
    },
    espn: {
      thumbnail: '/static/Images/home/foryou/apps/espn.png',
      title: 'MasterClass',
    },
  },
};
