export default {
  gridlist: ['now', 'upcoming', 'contWatch', 'music', 'apps', 'avengers'],
  now: {
    items: ['espn', 'cnn', 'ytube1', 'ytube2'],
    title: 'On Now',
    name: 'now',
    itemType: 'sqrThumb',
    espn: {
      title: '2018 NHL Playoffs: San Jose',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/espn.png',
      thumbnail: '/static/Images/home/foryou/onNow/espn1.png',
      startTime: 'live',
    },
    cnn: {
      title: 'CNN Live',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 7:00PM',
      logo: '/static/Images/home/foryou/icons/cnn.png',
      thumbnail: '/static/Images/home/foryou/onNow/cnn1.png',
      startTime: 'live',
    },
    ytube1: {
      title: 'American Idol 2018',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube1.png',
      startTime: 'live',
    },
    ytube2: {
      title: 'Wild India',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube2.png',
      startTime: 'live',
    },
  },
  upcoming: {
    items: ['twitch', 'ytube1', 'espn', 'amazon'],
    title: 'Upcoming',
    name: 'upcoming',
    itemType: 'sqrThumb',
    twitch: {
      title: 'Fnatic vs. Flash Wolves',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'Group Stage Day 4',
      logo: '/static/Images/home/foryou/icons/twitch.png',
      thumbnail: '/static/Images/home/foryou/upcoming/twitch.png',
      startTime: '8:00 PM',
    },
    ytube1: {
      title: 'CNN Live',
      gist: 'Tennis Channel ATP Final',
      subtitle: '2018 Barclays ATP World Tour',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/upcoming/ytube1.png',
      startTime: '9:00 PM',
    },
    espn: {
      title: 'American Idol 2018',
      gist: 'NBA Finals',
      subtitle: 'Warriors vs. Rockets',
      logo: '/static/Images/home/foryou/icons/espn.png',
      thumbnail: '/static/Images/home/foryou/upcoming/espn1.png',
      startTime: '8:00 PM',
    },
    amazon: {
      title: 'Wild India',
      gist: 'iZombie',
      subtitle: 'Season 5',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/upcoming/amazon.png',
      startTime: '8:00 PM',
    },
  },
  contWatch: {
    name: 'continue',
    items: ['ytube1', 'hulu', 'amazon', 'hulu1'],
    title: 'Continue Watching',
    itemType: 'sqrThumb',
    ytube1: {
      title: 'Black Mirror',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S3 E2',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/continue/ytube1.png',
    },
    hulu: {
      title: 'The Expanse',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S2 E5',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu.png',
    },
    amazon: {
      title: 'Avengers Infinity War',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '2018',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/continue/amazon.png',
    },
    hulu1: {
      title: 'Stranger Things',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu1.png',
    },
  },
  music: {
    items: ['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'item7'],
    itemType: 'recThumb',
    name: 'music',
    title: 'Recent Music',
    item1: {
      title: 'A Moment',
      subtitle: 'Odesza',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item1.png',
    },
    item2: {
      title: 'California',
      subtitle: 'Diplo',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item2.png',
    },
    item3: {
      title: 'No Reason',
      subtitle: 'Giraffage',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item3.png',
    },
    item4: {
      title: 'Hard to Say No',
      subtitle: 'Chromeo',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item4.png',
    },
    item5: {
      title: 'Ivory',
      subtitle: 'Tez Candey',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item5.png',
    },
    item6: {
      title: 'Your Daily Mix',
      subtitle: '',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item6.png',
    },
    item7: {
      title: 'Seve',
      subtitle: 'Tez Candey',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item7.png',
    },
  },
  avengers: {
    items: ['item1', 'item2', 'item3', 'item4'],
    title: 'Avengers',
    name: 'avengers',
    itemType: 'sqrThumb',
    item1: {
      title: 'Captain America: Civil War',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/avenger/item1.png',
    },
    item2: {
      title: 'Avengers: Age of Ultron',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/avenger/item2.png',
    },
    item3: {
      title: 'Avengers Infinity War',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/avenger/item3.png',
    },
    item4: {
      title: 'The Avengers',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/avenger/item4.png',
    },
  },
  apps: {
    items: ['netflix', 'hulu', 'amazon', 'spotify', 'youtube', 'espn'],
    itemType: 'sqr',
    name: 'apps',
    title: 'Recent Apps',
    netflix: {
      thumbnail: '/static/Images/home/foryou/apps/netflix.png',
      title: 'NetFlix',
    },
    hulu: {
      thumbnail: '/static/Images/home/foryou/apps/hulu.png',
      title: 'Hulu',
    },
    amazon: {
      thumbnail: '/static/Images/home/foryou/apps/amazon.png',
      title: 'Amazon',
    },
    spotify: {
      thumbnail: '/static/Images/home/foryou/apps/spotify.png',
      title: 'Spotify',
    },
    youtube: {
      thumbnail: '/static/Images/home/foryou/apps/youtube.png',
      title: 'Fitbit',
    },
    espn: {
      thumbnail: '/static/Images/home/foryou/apps/espn.png',
      title: 'MasterClass',
    },
  },
  pages: {
    pagination: ['health-1', 'health-2', 'health-3'],
    focusIdx: 0,
    details: {
      'health-1': {
        title: 'health-1',
        suggestions: ['Hey Bixby, continue watching The Handmaid’s Tale'],
        nav: [
          ['poster', 'tile1'],
          ['poster', 'tile2'],
        ],
        content: ['fitbit', 'body', 'friendly'],
        fitbit: {
          type: 'poster',
          template: 'poster',
          contentType: 'simple',
          details: {
            full: 'full',
            video: '/resources/videos/smartscreen/TV_Shows_1_Westworld.mp4',
            poster: '/static/Images/home/posters/morning/fitbit.png',
            text1: '<span><span style="color: rgba(255,97,97,1);">Westworld</span> <br> <span>2 Seasons | 20 Episodes</span></span>',
            logo: '/static/Images/home/foryou/slidesIcons/amazon.png',
            logoType: 'sqr',
            img: '',
          },
        },
        body: {
          type: 'tile1',
          template: 'tile',
          contentType: 'simple',
          details: {
            full: 'partial',
            action: {
              category: 'hulu',
              subcategory: 'home',
              content: 'handmaids',
            },
            topLeftText: '<span class="bold-top-text">Continue Watching</span>',
            bottomText: '<span>Daily 5-min <span style="color: rgba(42,109,156,1);">Body Tone</span></span>',
            tile: '/static/Images/home/tile/morning/body.png',
            logo: '/static/Images/home/foryou/slidesIcons/daily.png',
            logoType: 'rect',
            img: '',
          },
        },
        friendly: {
          type: 'tile2',
          template: 'tile',
          contentType: 'simple',
          details: {
            full: 'partial',
            action: {
              category: 'hulu',
              subcategory: 'home',
              content: 'handmaids',
            },
            topLeftText: '<span class="bold-top-text">Continue Watching</span>',
            bottomText: '<span>Apartment-friendly <span style="color: rgba(42,109,156,1);">Ab Workout</span></span>',
            tile: '/static/Images/home/tile/morning/friendly.png',
            logo: '/static/Images/home/foryou/slidesIcons/cody.png',
            logoType: 'rect',
            img: '',
          },
        },
      },
      'health-2': {
        title: 'health-2',
        suggestions: ['Hey Bixby, go to Fitbit'],
        content: ['meditation', 'shealth'],
        nav: [
          ['hTile', 'poster', 'poster'],
          ['hTile', 'poster', 'poster'],
        ],
        meditation: {
          type: 'hTile',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: false,
            hTile: '/static/Images/home/hTile/morning/meditation.png',
            text1: '<span style="color: rgba(42,109,156,1);">3-min Meditation</span>',
            logo: '/static/Images/home/foryou/slidesIcons/cody.png',
            logoType: 'sqr',
            img: '',
          },
        },
        shealth: {
          type: 'poster',
          template: 'poster',
          contentType: 'simple',
          details: {
            full: true,
            video: '/resources/videos/smartscreen/TV_Shows_2_Six_feet_under.mp4',
            poster: '/static/Images/home/posters/morning/shealth.png',
            text1: '<span>How to Prepare for <span style="color: rgba(42,109,156,1);">Your First 5k</span></span>',
            logo: '/static/Images/home/foryou/slidesIcons/shealth.png',
            logoType: 'sqr',
            img: '',
          },
        },
      },
      'health-3': {
        title: 'health-3',
        suggestions: ['Hey Bixby, play my Classical Playlist'],
        content: ['lesson', 'meal', 'balance', 'stress'],
        nav: [
          ['hTile1', 'hTile2', 'tile1'],
          ['hTile1', 'hTile2', 'tile2'],
        ],
        lesson: {
          type: 'hTile1',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: false,
            video: '/resources/videos/smartscreen/TV_Shows_3_True_detective.mp4',
            hTile: '/static/Images/home/hTile/morning/lesson.png',
            text1: '<span>Lesson 3: <span style="color: rgba(42,109,156,1);">Barre Basics</span></span>',
            logo: '/static/Images/home/foryou/slidesIcons/cody.png',
            logoType: 'sqr',
            img: '',
          },
        },
        meal: {
          type: 'hTile2',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: false,
            video: '/resources/videos/smartscreen/TV_Shows_3_True_detective.mp4',
            hTile: '/static/Images/home/hTile/morning/meal.png',
            text1: '<span><span style="color: rgba(42,109,156,1);">Meap Prep</span> Sundays</span>',
            logo: '/static/Images/home/foryou/slidesIcons/food.png',
            logoType: 'sqr',
            img: '',
          },
        },
        balance: {
          type: 'tile1',
          template: 'tile',
          contentType: 'simple',
          details: {
            full: true,
            tile: '/static/Images/home/tile/morning/balance.png',
            bottomText: '<span>Day 2:<span style="color: rgba(42,109,156,1);">Balance</span></span>',
            logo: '/static/Images/home/foryou/slidesIcons/headspace.png',
            logoType: 'rect-3',
            img: '/static/Images/home/page1/poster.png',
          },
        },
        stress: {
          type: 'tile2',
          template: 'tile',
          contentType: 'simple',
          details: {
            full: true,
            tile: '/static/Images/home/tile/morning/stress.png',
            bottomText: '<span>Day 8:<span style="color: rgba(42,109,156,1);">Stress Visualization</span></span>',
            logo: '/static/Images/home/foryou/slidesIcons/headspace.png',
            logoType: 'rect-3',
            img: '/static/Images/home/page1/poster.png',
          },
        },
      },
    },
  },
};
