export default {
  gridlist: ['now', 'upcoming', 'contWatch', 'music', 'apps', 'avengers'],
  now: {
    items: ['espn', 'cnn', 'ytube1', 'ytube2'],
    title: 'On Now',
    name: 'now',
    itemType: 'sqrThumb',
    espn: {
      title: '2018 NHL Playoffs: San Jose',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/espn.png',
      thumbnail: '/static/Images/home/foryou/onNow/espn1.png',
      startTime: 'live',
    },
    cnn: {
      title: 'CNN Live',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 7:00PM',
      logo: '/static/Images/home/foryou/icons/cnn.png',
      thumbnail: '/static/Images/home/foryou/onNow/cnn1.png',
      startTime: 'live',
    },
    ytube1: {
      title: 'American Idol 2018',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube1.png',
      startTime: 'live',
    },
    ytube2: {
      title: 'Wild India',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '6:00 - 8:00PM',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/onNow/ytube2.png',
      startTime: 'live',
    },
  },
  upcoming: {
    items: ['twitch', 'ytube1', 'espn', 'amazon'],
    title: 'Upcoming',
    name: 'upcoming',
    itemType: 'sqrThumb',
    twitch: {
      title: 'Fnatic vs. Flash Wolves',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'Group Stage Day 4',
      logo: '/static/Images/home/foryou/icons/twitch.png',
      thumbnail: '/static/Images/home/foryou/upcoming/twitch.png',
      startTime: '8:00 PM',
    },
    ytube1: {
      title: 'CNN Live',
      gist: 'Tennis Channel ATP Final',
      subtitle: '2018 Barclays ATP World Tour',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/upcoming/ytube1.png',
      startTime: '9:00 PM',
    },
    espn: {
      title: 'American Idol 2018',
      gist: 'NBA Finals',
      subtitle: 'Warriors vs. Rockets',
      logo: '/static/Images/home/foryou/icons/espn.png',
      thumbnail: '/static/Images/home/foryou/upcoming/espn1.png',
      startTime: '8:00 PM',
    },
    amazon: {
      title: 'Wild India',
      gist: 'iZombie',
      subtitle: 'Season 5',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/upcoming/amazon.png',
      startTime: '8:00 PM',
    },
  },
  contWatch: {
    name: 'continue',
    items: ['ytube1', 'hulu', 'amazon', 'hulu1'],
    title: 'Continue Watching',
    itemType: 'sqrThumb',
    ytube1: {
      title: 'Black Mirror',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S3 E2',
      logo: '/static/Images/home/foryou/icons/youtube.png',
      thumbnail: '/static/Images/home/foryou/continue/ytube1.png',
    },
    hulu: {
      title: 'The Expanse',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S2 E5',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu.png',
    },
    amazon: {
      title: 'Avengers Infinity War',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: '2018',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/continue/amazon.png',
    },
    hulu1: {
      title: 'Stranger Things',
      gist: 'Sharks vs. Anaheim Ducks',
      subtitle: 'S1 E6',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/continue/hulu1.png',
    },
  },
  music: {
    items: ['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'item7'],
    itemType: 'recThumb',
    name: 'music',
    title: 'Recent Music',
    item1: {
      title: 'A Moment',
      subtitle: 'Odesza',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item1.png',
    },
    item2: {
      title: 'California',
      subtitle: 'Diplo',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item2.png',
    },
    item3: {
      title: 'No Reason',
      subtitle: 'Giraffage',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item3.png',
    },
    item4: {
      title: 'Hard to Say No',
      subtitle: 'Chromeo',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item4.png',
    },
    item5: {
      title: 'Ivory',
      subtitle: 'Tez Candey',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item5.png',
    },
    item6: {
      title: 'Your Daily Mix',
      subtitle: '',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item6.png',
    },
    item7: {
      title: 'Seve',
      subtitle: 'Tez Candey',
      logo: '/static/Images/home/foryou/icons/spotify.png',
      thumbnail: '/static/Images/home/foryou/music/item7.png',
    },
  },
  avengers: {
    items: ['item1', 'item2', 'item3', 'item4'],
    title: 'Avengers',
    name: 'avengers',
    itemType: 'sqrThumb',
    item1: {
      title: 'Captain America: Civil War',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/avenger/item1.png',
    },
    item2: {
      title: 'Avengers: Age of Ultron',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/avenger/item2.png',
    },
    item3: {
      title: 'Avengers Infinity War',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/amazon.png',
      thumbnail: '/static/Images/home/foryou/avenger/item3.png',
    },
    item4: {
      title: 'The Avengers',
      subtitle: '2016',
      logo: '/static/Images/home/foryou/icons/hulu.png',
      thumbnail: '/static/Images/home/foryou/avenger/item4.png',
    },
  },
  apps: {
    items: ['netflix', 'hulu', 'amazon', 'spotify', 'youtube', 'espn'],
    itemType: 'sqr',
    name: 'apps',
    title: 'Recent Apps',
    netflix: {
      thumbnail: '/static/Images/home/foryou/apps/netflix.png',
      title: 'NetFlix',
    },
    hulu: {
      thumbnail: '/static/Images/home/foryou/apps/hulu.png',
      title: 'Hulu',
    },
    amazon: {
      thumbnail: '/static/Images/home/foryou/apps/amazon.png',
      title: 'Amazon',
    },
    spotify: {
      thumbnail: '/static/Images/home/foryou/apps/spotify.png',
      title: 'Spotify',
    },
    youtube: {
      thumbnail: '/static/Images/home/foryou/apps/youtube.png',
      title: 'Fitbit',
    },
    espn: {
      thumbnail: '/static/Images/home/foryou/apps/espn.png',
      title: 'MasterClass',
    },
  },
  pages: {
    pagination: ['movie-1', 'movie-2', 'movie-3'],
    focusIdx: 0,
    details: {
      'movie-1': {
        title: 'movie-1',
        suggestions: ['Hey Bixby, continue watching The Handmaid’s Tale'],
        nav: [
          ['poster', 'hTile'],
          ['poster', 'hTile'],
        ],
        content: ['tomraider', 'everyday'],
        tomraider: {
          type: 'poster',
          template: 'poster',
          contentType: 'simple',
          details: {
            full: true,
            video: '/resources/videos/smartscreen/TV_Shows_1_Westworld.mp4',
            poster: '/static/Images/home/posters/morning/tom.png',
            text1: '<span><span style="color: rgba(255,97,97,1);">Tomb Raider</span> <br> <span>2018</span></span>',
            logo: '/static/Images/home/foryou/slidesIcons/amazon.png',
            logoType: 'sqr',
            img: '',
          },
        },
        everyday: {
          type: 'hTile',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: true,
            hTile: '/static/Images/home/hTile/morning/everyday.png',
            text1: '',
            logo: '/static/Images/home/foryou/slidesIcons/starz.png',
            logoType: 'sqr',
            img: '',
          },
        },
      },
      'movie-2': {
        title: 'movie-2',
        suggestions: ['Hey Bixby, go to Fitbit'],
        content: ['coco', 'death', 'lala'],
        nav: [
          ['hTile1', 'hTile2', 'hTile3'],
          ['hTile1', 'hTile2', 'hTile3'],
        ],
        coco: {
          type: 'hTile1',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: true,
            hTile: '/static/Images/home/hTile/morning/coco.png',
            text1: '',
            logo: '/static/Images/home/foryou/slidesIcons/starz.png',
            logoType: 'sqr',
            img: '',
          },
        },
        death: {
          type: 'hTile2',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: true,
            hTile: '/static/Images/home/hTile/morning/death.png',
            text1: '',
            logo: '/static/Images/home/foryou/slidesIcons/netflix.png',
            logoType: 'sqr',
            img: '',
          },
        },
        lala: {
          type: 'hTile3',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: true,
            hTile: '/static/Images/home/hTile/morning/lala.png',
            text1: '',
            logo: '/static/Images/home/foryou/slidesIcons/amazon-w.png',
            logoType: 'sqr',
            img: '',
          },
        },
      },
      'movie-3': {
        title: 'movie-3',
        suggestions: ['Hey Bixby, play my Classical Playlist'],
        content: ['panther', 'mygirl', 'gamenight', 'deadpool', 'town', 'strong'],
        nav: [
          ['hTile1', 'hTile2', 'thumbnail1', 'thumbnail2'],
          ['hTile1', 'hTile2', 'thumbnail3', 'thumbnail4'],
        ],
        panther: {
          type: 'hTile1',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: true,
            video: '/resources/videos/smartscreen/TV_Shows_3_True_detective.mp4',
            hTile: '/static/Images/home/hTile/morning/panther.png',
            text1: '',
            logo: '/static/Images/home/foryou/slidesIcons/netflix.png',
            logoType: 'sqr',
            img: '',
          },
        },
        mygirl: {
          type: 'hTile2',
          template: 'hTile',
          contentType: 'simple',
          details: {
            full: true,
            video: '/resources/videos/smartscreen/TV_Shows_3_True_detective.mp4',
            hTile: '/static/Images/home/hTile/morning/mygirl.png',
            text1: '',
            logo: '/static/Images/home/foryou/slidesIcons/amazon-w.png',
            logoType: 'sqr',
            img: '',
          },
        },
        gamenight: {
          type: 'thumbnail1',
          template: 'thumbnail',
          contentType: 'cp-type-1',
          details: {
            full: 'full',
            icon: '',
            bottomText: '',
            logoType: 'text-big',
            logo: '/static/Images/home/foryou/slidesIcons/netflix.png',
            img: '/static/Images/home/thumbnail/morning/gamenight.png',
          },
        },
        deadpool: {
          type: 'thumbnail2',
          template: 'thumbnail',
          contentType: 'cp-type-1',
          details: {
            full: 'full',
            icon: '',
            bottomText: '',
            logoType: 'text-big',
            logo: '/static/Images/home/foryou/slidesIcons/amazon-w.png',
            img: '/static/Images/home/thumbnail/morning/deadpool.png',
          },
        },
        town: {
          type: 'thumbnail3',
          template: 'thumbnail',
          contentType: 'cp-type-1',
          details: {
            full: 'full',
            icon: '',
            bottomText: '',
            logoType: 'text-big',
            logo: '/static/Images/home/foryou/slidesIcons/amazon-w.png',
            img: '/static/Images/home/thumbnail/morning/town.png',
          },
        },
        strong: {
          type: 'thumbnail4',
          template: 'thumbnail',
          contentType: 'cp-type-1',
          details: {
            full: 'full',
            icon: '',
            bottomText: '',
            logoType: 'text-big',
            logo: '/static/Images/home/foryou/slidesIcons/starz.png',
            img: '/static/Images/home/thumbnail/morning/strong.png',
          },
        },
      },
    },
  },
};
